/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Alert.vue')['default']
    AlertError: typeof import('./src/components/alerts/AlertError.vue')['default']
    CreateUser: typeof import('./src/components/CreateUser.vue')['default']
    DeleteUser: typeof import('./src/components/DeleteUser.vue')['default']
    Error: typeof import('./src/components/alerts/Error.vue')['default']
    GetAllUsers: typeof import('./src/components/GetAllUsers.vue')['default']
    GetUser: typeof import('./src/components/GetUser.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Level: typeof import('./src/components/Level.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Success: typeof import('./src/components/alerts/Success.vue')['default']
    UpdateUser: typeof import('./src/components/UpdateUser.vue')['default']
  }
}
