import Head from "next/head";
import { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste omnis quam ipsam quia? Labore enim velit ut doloribus exercitationem cum ipsum tenetur. Libero culpa deserunt error, minus explicabo veritatis sed.
        </p>
      </main>
    </>
  );
};

export default Home;