import Head from "next/head";
import { NextPage } from "next";

const Products: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>
        Nossos Produtos
      </h1>
    </>
  );
};

export default Products;
